apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitor-node-service-monitor
  labels:
    release: prometheus
    app: prometheus
spec:
  jobLabel: job
  selector:
    matchLabels:
      app: monitor-node-service
  endpoints:
  - interval: 4s
    port: monitor-node-port
    path: /metrics