apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom-node-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prom-node
  template:
    metadata:
      labels:
        app: prom-node
    spec:
      containers:
        - name: prom-node-container
          image: prodanish203/kube-node-prom
          ports:
            - containerPort: 8000
