apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prom-node-service-monitor
  labels:
    release: prometheus
    app: prometheus
spec:
  jobLabel: job
  selector:
    matchLabels:
      app: prom-node-service
  endpoints:
  - interval: 30s
    port: prom-node-port
    path: /swagger-stats/metrics